# Copyright 2020-2022 Google, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runtime: python38

#automatic_scaling:
#instance_class: F4 

#use basic scaling for creating 5K or more tags in bulk
#use B4_1G when creating tags for large configs, up to 200 instances (500K+ tags)
instance_class: B4_1G
basic_scaling:
  max_instances: 200
  idle_timeout: 10m